### ISSUE TITLE
Maketile v2

### ISSUE THREAD

**Issue by edemaine** [edemaine/svgtiler#99]
Instead of inventing a language as in #84, let's use JavaScript/CoffeeScript! This let us use `for` loops and compilated `switch`/`if`...`else if`...`else` logic. For example (based on #96):

```coffee
export switched = ->
  for filename in svgtiler.glob '*.asc'
    switch
      when svgtiler.match filename, 'simple_*'
        svgtiler 'mapping1.coffee', filename
      else
        svgtiler 'mapping2.coffee', filename

export simple = ->
  svgtiler '''
    ( mapping1.coffee *.asc )
    ( mapping2.coffee *.xlsx )
  '''

export default both = ->
  simple()
  switched()

export {default as figures} from './figures/Maketile'

import figures1 from './figures1/Maketile'
import figures2 from './figures1/Maketile'
exports figures = ->
  figures1()
  figures2()
```

* [x] `Maketile.js`/`Maketile.coffee` run automatically by `svgtiler` without filename on command line
  * [x] `svgtiler directory-name` does the same for `directory-name/Maketile.*`
  * [x] Some options change default settings for svgtiler and still trigger `Maketile`. This allows tweaking the options via e.g. `svgtiler -f` or `svgtiler -w`. Perhaps `Maketile` executed if no filenames on command like (but note that some options that look like filenames might be rule names, and should be interpreted as such instead).
* [x] `svgtiler(['map1.js', 'drawing.asc'])` &mdash; array arguments treated as already parsed (nice for arbitrary filenames)
  * This is very close to existing `svgtiler.main` (perhaps better named `svgtiler.run`)
  * [x] Also allow passing in a `Mapping` or `Drawing` directly (via `svgtiler.require`, for example).
  * [x] Perhaps allow nested arrays too, for `for` loops, or else use `...`
  * [ ] Maybe also builders like `svgtiler.group(...)` for parenthesis-like behavior.
* [x] `svgtiler('map1.js drawing.asc')` &mdash; string argument(s) parsed like shell (nice for more like Makefile usage)
  * ~~Maybe also explicit calls like `svgtiler.shell(...)` vs `svgtiler.run(...)` for when e.g. you want to call on one directory name. Or maybe just use template literal idea below.~~ String vs. array argument seems like a better distinguisher.
  * [x] Allow comments via `#` and multiple lines
  * [x] We'll need shell-like quote and backslash parsing, to handle filenames with spaces or other special characters (e.g. `*`).
  * [x] Glob support
  * [x] Allow multiple arguments, including `Mapping` objects or arrays, to mix with previous type.
* [ ] ``svgtiler`map1.js ${new Mapping(...)}` `` in JS or `svgtiler"map1.js #{new Mapping(...)}"` in CS (template literal) is a possibility if we want a hybrid between the two. We can detect this via [the `raw` field in the first argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#raw_strings).
* [x] `Maketile.args` ~~`Maketile` without extension~~ could still be the simpler command-line arguments only (essentially wrapped by `svgtiler '''...'''` in CoffeeScript), as in #84 (but without rules)
* [x] Glob helpers that wrap our glob library, e.g. to loop over `*.{asc,xls*}` and check which type of processing you want to do.
  * [x] `svgtiler.glob(pattern)` to find all files matching given pattern (synchronously, ideally)
  * [x] `svgtiler.match(filename, pattern)` to test whether a file matches a given pattern.
  * [x] Maybe also want a glob filter, so we can do something like `svgtiler.filter(svgtiler.glob('*.asc'), '!simple_*')` to implement set operations as in #96. (Sadly JavaScript `Set`s don't have union/intersection...)
  * [x] Maybe allow glob array to be passed into `svgtiler`. Else need `...glob`, which is maybe hard to do in template literal.
  * [ ] Should be relative to Maketile (or mapping?) directory, not current directory
  * [ ] Maybe also allow RegExp arguments to `svgtiler.glob` and `svgtiler`
* [ ] Optimize: Check whether mappings are same as last invocation of `svgtiler` and don't reinitialize in this case.
  * Hmm, but this would break the contract that `onInit` gets called every time the mapping file is listed on the command line. So maybe not a good optimization.
  * Parens are less important in this view because we can just run `svgtiler` multiple times. Typically we imagine clustering among drawings in terms of how to process them.
* [x] Tasks/rules, perhaps via named exported functions (as opposed to `Cakefile`'s `task` function)
* [x] Use `export default` for main task, also so can call it from another (parent) Maketile
* [x] Implementation similar to `Mapping`, maybe a shared parent: Want JS/CS/JSX/`require` parsing similarly, but don't want `onInit`/`preprocess`/`postprocess`.
* [x] `--maketile alternative-maketile.coffee`, in particular to enable running rules from another Maketile
  * We can already recurse in a directory via `svgtiler('dirName')` or via `require('dirName/Maketile.js')()`.
  * Sadly `-m` is taken by `--margin`
* [ ] Potentially still compatible with watch mode `-w` (#74), with `svgtiler(...)` accumulating jobs into a list. Perhaps use of `svgtiler.glob('*.asc')` also causes rerun when new `.asc` file created.
* [x] Could implement `svgtiler --clean` by changing effect of `svgtiler` function to delete files that would be generated. (#84)
* [x] `svgtiler.needVersion('^3.1.0')` could allow specifying what version of SVG Tiler this is designed for (also in mapping files). (#84)
* [x] ~~`new InlineMapping -> ...` to simulate the code of a mapping file without a separate file? `...` could schedule callbacks via `svgtiler.preprocess` etc.~~ ~~#95~~ #100 provides an alternative for inline mappings without separate files.

**Comment by edemaine** [comment]
This is basically done; remaining ideas are speculative, or left to #74.
